# Base image for Spring Boot
FROM eclipse-temurin:21-jdk as build
WORKDIR /app
COPY ./backend/pom.xml ./backend/src/ ./
RUN ./mvnw package -DskipTests

# Production image
FROM eclipse-temurin:21-jre
WORKDIR /app
COPY --from=build /app/target/*.jar app.jar
ENTRYPOINT ["java", "-jar", "/app/app.jar"]
EXPOSE 8080
