services:
  proxy:
    build:
      context: ..
      dockerfile: ./Dockerfile.nginx
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
    networks:
      - bicycle-shop-network

  frontend:
    build:
      context: ..
      dockerfile: ./Dockerfile.frontend
    env_file:
      - ./env/${ENV_FILE:-dev.env}
    networks:
      - bicycle-shop-network
    depends_on:
      - backend

  backend:
    build:
      context: ..
      dockerfile: ./Dockerfile.backend
    env_file:
      - ./env/${ENV_FILE:-dev.env}
    depends_on:
      - db
    networks:
      - bicycle-shop-network

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: shop
    ports:
      - "5432:5432"
    networks:
      - bicycle-shop-network

networks:
  bicycle-shop-network:
    driver: bridge
