name: Build and Push Frontend Docker Image to GHCR

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the frontend repository (bicycle-shop-frontend)
      - name: Checkout frontend repository
        uses: actions/checkout@v4
        with:
          repository: ${{ github.actor }}/bicycle-shop-frontend
          path: frontend

      # Step 2: Checkout the infra repository (bicycle-shop-deployment) to get the Dockerfile
      - name: Checkout infra repository
        uses: actions/checkout@v4
        with:
          repository: ${{ github.actor }}/bicycle-shop-deployment
          path: deployment

      # Step 3: Set up Docker Buildx (optional, recommended for multi-platform builds)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Step 4: Log in to GitHub Container Registry (GHCR)
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Step 5: Build the Docker image using the Dockerfile from the infra repository
      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository }}/frontend:latest -f deployment/dockerfile.frontend ./bicycle-shop-frontend

      # Step 6: Push the Docker image to GHCR
      - name: Push Docker image to GHCR
        run: |
          docker push ghcr.io/${{ github.repository }}/frontend:latest
