name: Build and Push Backend Docker Image to GHCR

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the backend repository (bicycle-shop-backend)
      - name: Checkout backend repository
        uses: actions/checkout@v3

      # Step 2: Checkout the infra repository (bicycle-shop-deployment) to get the Dockerfile
      - name: Checkout infra repository
        uses: actions/checkout@v3
        with:
          repository: ${{ github.actor }}/bicycle-shop-deployment
          path: deployment

      # Step 3: Set up Docker Buildx (optional, recommended for multi-platform builds)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 4: Log in to GitHub Container Registry (GHCR)
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}

      # Step 5: Build the Docker image using the Dockerfile from the infra repository
      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository }}/backend:latest -f deployment/dockerfile.backend ./bicycle-shop-backend

      # Step 6: Push the Docker image to GHCR
      - name: Push Docker image to GHCR
        run: |
          docker push ghcr.io/${{ github.repository }}/backend:latest
